// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"chess-console/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGames creates a new instance of MockGames. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGames(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGames {
	mock := &MockGames{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGames is an autogenerated mock type for the Games type
type MockGames struct {
	mock.Mock
}

type MockGames_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGames) EXPECT() *MockGames_Expecter {
	return &MockGames_Expecter{mock: &_m.Mock}
}

// GetTurn provides a mock function for the type MockGames
func (_mock *MockGames) GetTurn() dto.Color {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTurn")
	}

	var r0 dto.Color
	if returnFunc, ok := ret.Get(0).(func() dto.Color); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(dto.Color)
	}
	return r0
}

// MockGames_GetTurn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTurn'
type MockGames_GetTurn_Call struct {
	*mock.Call
}

// GetTurn is a helper method to define mock.On call
func (_e *MockGames_Expecter) GetTurn() *MockGames_GetTurn_Call {
	return &MockGames_GetTurn_Call{Call: _e.mock.On("GetTurn")}
}

func (_c *MockGames_GetTurn_Call) Run(run func()) *MockGames_GetTurn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGames_GetTurn_Call) Return(color dto.Color) *MockGames_GetTurn_Call {
	_c.Call.Return(color)
	return _c
}

func (_c *MockGames_GetTurn_Call) RunAndReturn(run func() dto.Color) *MockGames_GetTurn_Call {
	_c.Call.Return(run)
	return _c
}

// IsGameOver provides a mock function for the type MockGames
func (_mock *MockGames) IsGameOver() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsGameOver")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGames_IsGameOver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsGameOver'
type MockGames_IsGameOver_Call struct {
	*mock.Call
}

// IsGameOver is a helper method to define mock.On call
func (_e *MockGames_Expecter) IsGameOver() *MockGames_IsGameOver_Call {
	return &MockGames_IsGameOver_Call{Call: _e.mock.On("IsGameOver")}
}

func (_c *MockGames_IsGameOver_Call) Run(run func()) *MockGames_IsGameOver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGames_IsGameOver_Call) Return(b bool) *MockGames_IsGameOver_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGames_IsGameOver_Call) RunAndReturn(run func() bool) *MockGames_IsGameOver_Call {
	_c.Call.Return(run)
	return _c
}

// IsValidMove provides a mock function for the type MockGames
func (_mock *MockGames) IsValidMove(sr int, sc int, er int, ec int, turn dto.Color) error {
	ret := _mock.Called(sr, sc, er, ec, turn)

	if len(ret) == 0 {
		panic("no return value specified for IsValidMove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, int, int, int, dto.Color) error); ok {
		r0 = returnFunc(sr, sc, er, ec, turn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGames_IsValidMove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValidMove'
type MockGames_IsValidMove_Call struct {
	*mock.Call
}

// IsValidMove is a helper method to define mock.On call
//   - sr int
//   - sc int
//   - er int
//   - ec int
//   - turn dto.Color
func (_e *MockGames_Expecter) IsValidMove(sr interface{}, sc interface{}, er interface{}, ec interface{}, turn interface{}) *MockGames_IsValidMove_Call {
	return &MockGames_IsValidMove_Call{Call: _e.mock.On("IsValidMove", sr, sc, er, ec, turn)}
}

func (_c *MockGames_IsValidMove_Call) Run(run func(sr int, sc int, er int, ec int, turn dto.Color)) *MockGames_IsValidMove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 dto.Color
		if args[4] != nil {
			arg4 = args[4].(dto.Color)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGames_IsValidMove_Call) Return(err error) *MockGames_IsValidMove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGames_IsValidMove_Call) RunAndReturn(run func(sr int, sc int, er int, ec int, turn dto.Color) error) *MockGames_IsValidMove_Call {
	_c.Call.Return(run)
	return _c
}

// Move provides a mock function for the type MockGames
func (_mock *MockGames) Move(sr int, sc int, er int, ec int, turn dto.Color) error {
	ret := _mock.Called(sr, sc, er, ec, turn)

	if len(ret) == 0 {
		panic("no return value specified for Move")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, int, int, int, dto.Color) error); ok {
		r0 = returnFunc(sr, sc, er, ec, turn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGames_Move_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Move'
type MockGames_Move_Call struct {
	*mock.Call
}

// Move is a helper method to define mock.On call
//   - sr int
//   - sc int
//   - er int
//   - ec int
//   - turn dto.Color
func (_e *MockGames_Expecter) Move(sr interface{}, sc interface{}, er interface{}, ec interface{}, turn interface{}) *MockGames_Move_Call {
	return &MockGames_Move_Call{Call: _e.mock.On("Move", sr, sc, er, ec, turn)}
}

func (_c *MockGames_Move_Call) Run(run func(sr int, sc int, er int, ec int, turn dto.Color)) *MockGames_Move_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 dto.Color
		if args[4] != nil {
			arg4 = args[4].(dto.Color)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGames_Move_Call) Return(err error) *MockGames_Move_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGames_Move_Call) RunAndReturn(run func(sr int, sc int, er int, ec int, turn dto.Color) error) *MockGames_Move_Call {
	_c.Call.Return(run)
	return _c
}

// Print provides a mock function for the type MockGames
func (_mock *MockGames) Print() {
	_mock.Called()
	return
}

// MockGames_Print_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Print'
type MockGames_Print_Call struct {
	*mock.Call
}

// Print is a helper method to define mock.On call
func (_e *MockGames_Expecter) Print() *MockGames_Print_Call {
	return &MockGames_Print_Call{Call: _e.mock.On("Print")}
}

func (_c *MockGames_Print_Call) Run(run func()) *MockGames_Print_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGames_Print_Call) Return() *MockGames_Print_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGames_Print_Call) RunAndReturn(run func()) *MockGames_Print_Call {
	_c.Run(run)
	return _c
}

// SwitchTurn provides a mock function for the type MockGames
func (_mock *MockGames) SwitchTurn() {
	_mock.Called()
	return
}

// MockGames_SwitchTurn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwitchTurn'
type MockGames_SwitchTurn_Call struct {
	*mock.Call
}

// SwitchTurn is a helper method to define mock.On call
func (_e *MockGames_Expecter) SwitchTurn() *MockGames_SwitchTurn_Call {
	return &MockGames_SwitchTurn_Call{Call: _e.mock.On("SwitchTurn")}
}

func (_c *MockGames_SwitchTurn_Call) Run(run func()) *MockGames_SwitchTurn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGames_SwitchTurn_Call) Return() *MockGames_SwitchTurn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGames_SwitchTurn_Call) RunAndReturn(run func()) *MockGames_SwitchTurn_Call {
	_c.Run(run)
	return _c
}
